services:
  APP:
    image: node:20-alpine
    command: sh -c "npm i && npm run dev"
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - 3003:3003
    depends_on:
      - BROKER
  VIEWS:
    image: node:20-alpine
    command: sh -c "npm i && npm start"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  BROKER:
    image: rabbitmq:4.0-alpine
    ports:
      - 5672:5672